scales_list <- list(
  perceived_risk = c("riskpers1", "riskpers2", "riskpers3", "riskfamfr1", "riskfamfr2", "riskfamfr3"),
  anxiety = c("anx1", "anx2", "anx3", "anx4", "anx5", "anx6", "anx7"),
  depression = c("dep1", "dep2", "dep3", "dep4", "dep5", "dep6", "dep7"),
  social_isolation = c("socisol1", "socisol2", "socisol3", "socisol4"),
  social_actions = c("freqcom1fam", "freqcom2fr", "freqcom3col", "freqcom4fam", "freqcom5fr", "freqcom6col", "freqcom7fam", "freqcom8fr", "freqcom9col"),
  sense_of_control = c("control_actdir", "control_lohi"),
  avoidance_actions = c("activ1_wash", "activ2_wash20", "activ3_stayhome", "activ4_disinfecthome", "activ5_antibactprod", "activ6_noface", "activ7_nohands", "activ8_nophys", "activ9_mask", "activ10_maskn95", "activ12_othersfood"),
  coping_actions = c("cope_active", "cope_plan", "cope_posrefr", "cope_accept", "cope_humour", "cope_relspir", "cope_emosup", "cope_instrumsup", "cope_distract", "cope_denial", "cope_vent", "cope_substan", "cope_giveup", "cope_selfblame"),
  freqcomcov = c("freqcomcov_fam", "freqcomcov_fr", "freqcomcov_col"),
  government_actions = c("govac1", "govac2", "govac3", "govac4", "govac5", "govac6"),
  gov_capab = c("gov_cap1", "gov_cap2"),
  gov_benevol = c("gov_benev1", "gov_benev2"),
  gov_trust = c("gov_trust1", "gov_trust2"),
  institutional_trust = c("gov_capab", "gov_benevol", "gov_trust"),
  govstate_capab = c("govstate_cap1", "govstate_cap2"),
  govstate_benevol = c("govstate_benev1", "govstate_benev2"),
  govstate_trust = c("govstate_trust1", "govstate_trust2"),
  instittruststate = c("govstate_capab", "govstate_benevol", "govstate_trust"),
  #trust_local = c("trustgov_country", "trustpers_country"),
  #trust_global = c("trustgov_global", "trustpers_global"),
  #trust_scient = c("trustscient_country", "trustscient_global"),
  feelinginformed = c("informed1", "informed2", "informed3", "informed4"),
  cope = c("cope1", "cope2", "cope3", "cope4", "cope5", "cope6", "cope7", 
           "cope8", "cope9", "cope10", "cope11", "cope12", "cope13", "cope14", 
           "cope15", "cope16", "cope17", "cope18", "cope19", "cope20", "cope21", 
           "cope22", "cope23", "cope24", "cope25", "cope26", "cope27", "cope28"
  )
)
